### ISSUE TITLE
SBCL type issue in class MESSAGE

### ISSUE THREAD

**Issue by wmannis** [binghe/cl-net-snmp#1]
It's been a while since I used this library. When I tried a few first tests again, I kept running into the error message that "" is not of type BASE-STRING. After some digging, I figure out it was a problem in handling contexts.

In SBCL 1.4.2 (on both Mac and Linux):

```common-lisp
* (typep "" 'string)
T
* (typep "" 'base-string)
NIL
```

This may be interacting with changes in SBCL [1.3.15](http://sbcl.org/all-news.html#1.3.15).

If I redefine the class `MESSAGE` so that `CONTEXT` has type `STRING` instead of `BASE-STRING`, things work properly for me again.

**Comment by binghe** [comment]
Thanks. You're right, `base-string` is not portable, I shouldn't use it. Now it's changed to `string`.

**Comment by wmannis** [comment]
Thanks!
